import Head from "next/head";
import Link from "next/link";

export default function FistPost() {
  return (
    <div>
      <Head>
        <title>最初の投稿</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>最初の投稿</h1>
      <Link href="/">ホームへ戻る</Link>
    </div>
  );
}
